# Generated by Django 4.2 on 2023-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk_photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_ak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_rk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.CharField(max_length=50)),
            ],
        ),
    ]
